name       : rhvoice
version    : 1.6.0
release    : 2
source     :
    - git|https://github.com/RHVoice/RHVoice.git : 1.6.0
license    : LGPL-2.1-only
component  : programming.library
summary    : a free and open source speech synthesizer for Russian and other languages
description: |
    RHVoice is a free and open-source speech synthesizer.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(libpulse-simple)
    - pkgconfig(speech-dispatcher)
    - pkgconfig(portaudio-2.0)
    - git
    - scons
rundeps    :
    - speech-dispatcher
environment: |
    DESTDIR=$installdir
    prefix=/usr
    sysconfdir="/usr/share/defaults"
setup      : |
    %patch -p1 < $pkgfiles/0001-speech-dispatcher-modules-path.patch
    sed -i 's#uncomment and edit the required parameters.#add "export RHVOICE_CONFIG_PATH=/etc/RHVoice" to .profile then copy file to edit it there.#g' $workdir/doc/en/RHVoice.conf
build      : |
    scons prefix=$prefix sysconfdir=$sysconfdir DESTDIR=$installdir
install    : |
    scons install prefix=$prefix sysconfdir=$sysconfdir DESTDIR=$installdir
    install -D -m 00644 $pkgfiles/rhvoice.conf $installdir/usr/share/defaults/speech-dispatcher/modules/rhvoice.conf
    install -D -m 00644 $workdir/doc/en/RHVoice.conf $installdir/usr/share/defaults/RHVoice/RHVoice.conf
